openapi: 3.0.3
info:
  title: Choreo Samples - Reading List - Nodejs REST API
  description: This is a sample API specification for a simple reading list application with in-memory cache written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:3000
tags:
  - name: books
    description: In-memory book list cache API
paths:
  /list:
    summary: List all books
    get:
      summary: List all books
      operationId: ListAllBooks
      tags:
        - books
      responses:
        "200":
          description: Successful operation
             
